### ISSUE TITLE
Bit-locker Cryptography We can Unlock it like Bios Modding

### ISSUE THREAD

**Issue by pk4tech** [dogbert/bios-pwgen#12]
Is there any way

**Comment by dogbert** [comment]
nope.

**Comment by pk4tech** [comment]
> nope.

Any other Way 😥 
Thanks For Reply😍😍

**Comment by imranromi** [comment]
> > nope.
> 
> Any other Way 😥 Thanks For Reply😍😍

Yes can via bios modified bitlocker unlock.
