### ISSUE TITLE
Fujitsu 6x4 hex code support

### ISSUE THREAD

**Issue by TheRaconZ** [dogbert/bios-pwgen#14]
Hi, I have a Fujitsu Lifebook U758 and there is a 6x4 hex code. Currently only the 5x4 hex or the 6x4 dec codes are supported by your scripts, but there are dubious providers who advertise passwords for 6x4 hex.
I already tried your downloadable python scripts and also https://beta.bios-pw.org/ and https://www.bios-pw.org/ but nothing worked.

Please can you add 6x4 hex password generation.
My code is: 203c-d001-a0fb-af9d-e7df-a82b

Thanks a lot

**Comment by dogbert** [comment]
I'm not developing this actively anymore - please use the fujitsu support
