### ISSUE TITLE
History?

### ISSUE THREAD

**Issue by EvanCarroll** [dogbert/bios-pwgen#2]
i would love to see the history for these. i'm not sure if you found these salts online, or discovered them yourself. I'd love to know how you went about finding the insyde salt. 

https://github.com/dogbert/bios-pwgen/blob/master/pwgen-insyde.py#L27

There is a problem with the i-series codes and I would love how I could apply methods to newer firmwares 

* https://github.com/bacher09/pwgen-for-bios/issues/52

**Comment by dogbert** [comment]
not an issue

**Comment by EvanCarroll** [comment]
teach me to fish please. =(
