### ISSUE TITLE
Fujitsu Lifebook E559 with 6 x 4 hex code

### ISSUE THREAD

**Issue by daLuiz** [dogbert/bios-pwgen#6]
I have a Fujitsu Lifebook E559, and it produces a 6x4 hex code like this:
aaaa-bbbb-cccc-dddd-eeee-ffff

The generators for the 6x4 decimal and 5x4 hex don't work with this code. Any Ideas how to incorporate this format into your collection of scripts? I am willing to help you test, if needed.

**Comment by chromer030** [comment]
Did you tried here : https://beta.bios-pw.org/ ?

**Comment by daLuiz** [comment]
I tried https://www.bios-pw.org before, but https://beta.bios-pw.org seems to do the exact same thin. The site does nothing if I enter the 6x4 hex code. If i remove the last block, it assumes it to be a 5x4 hex code and gives me a password, which does not work. I found a few people online who offer this as a paid service, mentioning 6x4 hex explicitly, so it must be possible, for example [here](https://biospassmaster.com/product-category/bios-master-passwords/fujitsu-bios-master-passwords/) or [here](https://bios-fix.com/index.php?resources/unlock-fujitsu-siemens-bios-password-new-models.213/)

**Comment by av2k** [comment]
@daLuiz It does indeed work.

Two things you should be aware of:

Run https://github.com/dogbert/bios-pwgen/blob/master/pwgen-fsi-6x4dec.py with a python2 interpreter, either on your system or on any online python2 interpreter like https://tio.run/#python2 (just found this site through a Google search, it offers a free python2 interpreter as of 19.05.2021).

Enter the code your BIOS shows (in the online interpreter, you can enter it under "input").

Then restart your PC with the locked BIOS, enter the BIOS and then the password the script gives you, **_but remember that you will have a QWERTY keyboard_**! Meaning that, for example, you'll have to replace any "y" for a "z" and vice versa in case you have a QWERTZ keyboard.

**Comment by daLuiz** [comment]
@av2k Thanks, but it does not work for a 6x4 hex code (1a2b-3c4d-5e6f-7a8b-9c0d-1e2f). It works for 6x4 decimal (0123-4567-8901-2345-6789-0123). 

Running it on python 2, in line 30 the line `numbers = (int(code[0:5]), int(code[5:10]), int(code[10:15]), int(code[15:20]))` cannot work, since you cant just convert hexadecimal numbers to integer, so it fails with `ValueError: invalid literal for int() with base 10: 'd001d'`. 

Also I am sure the algorithm is a little more complex in the 6x4 hex version than 6x4 dec. I am afraid this kind of code, which only appears on newer FSI notebooks, since about 2019, will require some more involved reverse engineering.

**Comment by av2k** [comment]
@daLuiz Is your code completely mixed or does it only contain hex letters in the first of the six four-character blocks?

**Comment by daLuiz** [comment]
> @daLuiz Is your code completely mixed or does it only contain hex letters in the first of the six four-character blocks?

There are letters in all of the 6 blocks.

**Comment by av2k** [comment]
What's strange is that it indeed works for codes where the first code contains a hex letter.

**Comment by daLuiz** [comment]
Line 86 of the code cuts off the first 4 letters of the decimal code, so they are not used in the calculation.

**Comment by fschmidteu** [comment]
Same issue over here: 
Model: E549 
Hexcode: 203c-d001-f4c0-bf56-9135-a8bb

**Comment by dogbert** [comment]
not an issue, but a feature request
